### ISSUE TITLE
about bin weights

### ISSUE THREAD

**Issue by namepllet** [facebookresearch/ContactOpt#7]
Could you explain how the weights in class_bin_weights.out are calculated ??

**Comment by pgrady3** [comment]
Hi, apologies for the late reply. Due to the uneven distribution of classes (mostly zeros in the dataset), we found that weighting the uncommon classes higher in the loss function produced better results, especially when tested on unseen objects. Here is the excerpt of code that was used to generate that file. The `histogram` variable is the pre-computed class frequency.

```
DAMPING = 1.0
histogram = [36265350, 14278068,  3364023,  1697927, 1196913, 1070915,  1032953,  1181615,  1708205,  2139535]
probs = histogram / np.sum(histogram)
weights = DAMPING * probs + (1-DAMPING) * np.ones(probs.shape) / probs.size
invw = 1 / weights
invw /= np.dot(invw, probs)
np.save(BIN_WEIGHTS_FILE, invw)
```

**Comment by namepllet** [comment]
Thanks !!
